services:
  app:
    image: node:24
    working_dir: /app
    tty: true
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./src:/app
      - ./data:/data
    environment:
      - WATCHPACK_POLLING=true
      - DATABASE_URL=file:/data/database.db
    command: >
      sh -c "npm run dev"
